import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { cart, cartItem } from "../interfaces/cartItems"
import { GetServerSideProps } from 'next'
import axios from 'axios'
import HomePage from './home'

const Home: NextPage = (data) => {
    
  return (
    <div>
      <Head>
        <title>Typescript Demo - shopping cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <HomePage/>
      </div>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {      
               const response = await axios.get(`http://localhost:3500/products`)
                return {
                        props:
                        {
                        data:response.data
                        }
        } 
        
}

export default Home
